config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :scout_branches
  resources :competences
  resources :game_types
  resources :games
  resources :users
  
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :email, :password, :registration_number)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="row">
    <div class="col-12">
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="col-6">
      <div class="field form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control" %>
      </div>
    </div>
    <div class="col-6">
      <div class="field form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="col-6">
      <div class="field form-group">
        <%= form.label :password %>
        <%= form.text_field :password, class: "form-control", type: "password" %>
      </div>
    </div>
    <div class="col-6">
      <div class="field form-group">
        <%= form.label :registration_number %>
        <%= form.text_field :registration_number, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col actions">
      <%= form.submit nil, class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%=t('form_title.editing_user')%></h1>

<%= render 'form', user: @user %>

  <%= link_to t('form_options.show'), @user, class: "btn btn-outline-secondary mt-2", type: "button" %>
  <%= link_to t('form_options.back'), users_path, class: "btn btn-outline-secondary mt-2", type: "button" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @users.model_name.human(count:2) %></h1>
<div class="row">
  <div class="col-12">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th scope="col"><%= @users.human_attribute_name :first_name%></th>
          <th scope="col"><%= @users.human_attribute_name :email%></th>
          <th scope="col"><%= @users.human_attribute_name :registration_number%></th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.email %></td>
            <td><%= user.registration_number %></td>
            <td> <i class="fas fa-eye"></i> <%= link_to t('form_options.show'), user %></td>
            <td><%= link_to t('form_options.edit'), edit_user_path(user) %></td>
            <td><%= link_to t('form_options.destroy'), user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>

<%= link_to t('form_options.new'), new_user_path, class: "btn btn-primary", type: "button" %>

app/views/users/new.html.erb
<h1><%=t('form_title.new_user')%></h1>

<%= render 'form', user: @user %>

<%= link_to t('form_options.back'), users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-6">
    <div class="field form-group">
      <%= label_tag nil, @user.class.human_attribute_name(:first_name) %>
      <%= text_field_tag nil, @user.first_name, class: "form-control", disabled: true %>
    </div>
  </div>
 <div class="col-6">
    <div class="field form-group">
      <%= label_tag nil, @user.class.human_attribute_name(:email) %>
      <%= text_field_tag nil,  @user.email, class: "form-control", disabled: true %>
    </div>
  </div>
  <div class="col-6">
    <div class="field form-group">
      <%= label_tag nil, @user.class.human_attribute_name(:password) %>
      <%= text_field_tag nil,  @user.password, class: "form-control", disabled: true, type: "password" %>
    </div>
  </div>
  <div class="col-6">
    <div class="field form-group">
      <%= label_tag nil, @user.class.human_attribute_name(:registration_number) %>
      <%= text_field_tag nil,  @user.registration_number, class: "form-control", disabled: true %>
    </div>
  </div>
</div>
<%= link_to t('form_options.edit'), edit_user_path(@user), class: "btn btn-outline-secondary mt-2" %>
<%= link_to t('form_options.back'), users_path, class: "btn btn-outline-secondary mt-2" %>