config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :scout_branches
  resources :competences
  resources :game_types
  resources :games
  resources :users
  
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/game_types_controller.rb
class GameTypesController < ApplicationController
  before_action :set_game_type, only: [:show, :edit, :update, :destroy]

  # GET /game_types
  # GET /game_types.json
  def index
    @game_types = GameType.all
  end

  # GET /game_types/1
  # GET /game_types/1.json
  def show
  end

  # GET /game_types/new
  def new
    @game_type = GameType.new
  end

  # GET /game_types/1/edit
  def edit
  end

  # POST /game_types
  # POST /game_types.json
  def create
    @game_type = GameType.new(game_type_params)

    respond_to do |format|
      if @game_type.save
        format.html { redirect_to @game_type, notice: 'Game type was successfully created.' }
        format.json { render :show, status: :created, location: @game_type }
      else
        format.html { render :new }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_types/1
  # PATCH/PUT /game_types/1.json
  def update
    respond_to do |format|
      if @game_type.update(game_type_params)
        format.html { redirect_to @game_type, notice: 'Game type was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_type }
      else
        format.html { render :edit }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_types/1
  # DELETE /game_types/1.json
  def destroy
    @game_type.destroy
    respond_to do |format|
      format.html { redirect_to game_types_url, notice: 'Game type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_type
      @game_type = GameType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_type_params
      params.require(:game_type).permit(:description)
    end
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/views/game_types/_form.html.erb
<%= form_with(model: game_type, local: true) do |form| %>
  <div class="row">
    <div class="col-12">
      <% if game_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(game_type.errors.count, "error") %> prohibited this game_type from being saved:</h2>

          <ul>
            <% game_type.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="col-6 field form-group">
      <%= form.label :description %>
      <%= form.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col actions">
      <%= form.submit nil, class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/game_types/edit.html.erb
<h1><%=t('form_title.editing_game_type')%></h1>

<%= render 'form', game_type: @game_type %>

<%= link_to t('form_options.show'), @game_type, class: "btn btn-outline-secondary mt-2" %> 
<%= link_to t('form_options.back'), game_types_path, class: "btn btn-outline-secondary mt-2" %>

app/views/game_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @game_types.model_name.human(count:2) %></h1>
<div class="row">
  <div class="col-12">
    <table class="table  table-responsive">
      <thead>
        <tr>
          <th scope="col"><%= @game_types.human_attribute_name :description%></th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @game_types.each do |game_type| %>
          <tr>
            <td><%= game_type.description %></td>
            <td><%= link_to t('form_options.show'), game_type %></td>
            <td><%= link_to t('form_options.edit'), edit_game_type_path(game_type) %></td>
            <td><%= link_to t('form_options.destroy'), game_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to t('form_options.new'), new_game_type_path, class: "btn btn-primary", type: "button" %>

app/views/game_types/new.html.erb
<h1><%=t('form_title.new_game_type')%></h1>

<%= render 'form', game_type: @game_type %>

<%= link_to t('form_options.back'), game_types_path %>

app/views/game_types/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-6">
    <%= label_tag nil, @game_type.class.human_attribute_name(:description) %>
    <%= text_field_tag nil, @game_type.description, class: "form-control", disabled: true %>
  </div>
</div>

<%= link_to t('form_options.edit'), edit_game_type_path(@game_type), class: "btn btn-outline-secondary mt-2" %> 
<%= link_to t('form_options.back'), game_types_path, class: "btn btn-outline-secondary mt-2" %>