config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :scout_branches
  resources :competences
  resources :game_types
  resources :games
  resources :users
  
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:place_type)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <div class="row">
    <div class="col-12">
      <% if place.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

          <ul>
            <% place.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="col-12 col-lg-6">
      <div class="field form-group">
        <%= form.label :place_type %>
        <%= form.text_field :place_type, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col actions">
      <%= form.submit nil, class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1><%=t('form_title.editing_place')%></h1>

<%= render 'form', place: @place %>

<%= link_to t('form_options.show'), @place, class: "btn btn-outline-secondary mt-2" %>
<%= link_to t('form_options.back'), places_path, class: "btn btn-outline-secondary mt-2" %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<div class="row">
  <div class="col-12">
    <table class="table  table-responsive">
      <thead>
        <tr>
          <th scope="col"><%= @places.human_attribute_name :place_type %></th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @places.each do |place| %>
          <tr>
            <td><%= place.place_type %></td>
            <td><%= link_to t('form_options.show'), place %></td>
            <td><%= link_to t('form_options.edit'), edit_place_path(place) %></td>
            <td><%= link_to t('form_options.destroy'), place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to t('form_options.new'), new_place_path, class: "btn btn-primary", type: "button" %>

app/views/places/new.html.erb
<h1><%=t('form_title.new_place')%></h1>

<%= render 'form', place: @place %>

<%= link_to t('form_options.back'), places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-12 col-lg-6">
    <%= label_tag nil, @place.class.human_attribute_name(:place_type) %>
    <%= text_field_tag nil, @place.place_type, class: "form-control", disabled: true %>
  </div>
</div>

<%= link_to t('form_options.edit'), edit_place_path(@place), class: "btn btn-outline-secondary mt-2" %>
<%= link_to t('form_options.back'), places_path, class: "btn btn-outline-secondary mt-2" %>